plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.compose'
}
android {
    namespace 'dev.zxcwsurx.zetacard'
    compileSdk 37
    defaultConfig {
        applicationId 'dev.zxcwsurx.zetacard'
        minSdk 29
        targetSdk 35
        versionCode = (project.findProperty('appVersionCode') ?: '110').toString().toInteger()
        versionName = (project.findProperty('appVersionName') ?: '1.1').toString()
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures { compose true }
    packaging {
        dex {
            useLegacyPackaging = true
        }
    }
}
dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    implementation platform('androidx.compose:compose-bom:2026.09.00')
    implementation 'androidx.activity:activity-compose:1.11.0'
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.material3:material3:1.5.0-alpha29'
    implementation 'androidx.compose.material:material-icons-extended'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
}
